/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiSetting: typeof import('./../components/ApiSetting/index.vue')['default']
    ApiSettingChatModel: typeof import('./../components/ApiSetting/ChatModel.vue')['default']
    Chart: typeof import('./../components/Chart/index.vue')['default']
    ClochatChatSettings: typeof import('./../components/Clochat/ChatSettings/index.vue')['default']
    ClockTime: typeof import('./../components/ClockTime/index.vue')['default']
    GhostButton: typeof import('./../components/GhostButton.vue')['default']
    InfiniteScrollList: typeof import('./../components/InfiniteScrollList/index.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    NavTimeBar: typeof import('./../components/NavTimeBar.vue')['default']
    Popconfirm: typeof import('./../components/Popconfirm/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
